CREATE TABLE IF NOT EXISTS e_documents (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id BIGINT UNSIGNED NOT NULL,
 provider VARCHAR(50) NOT NULL DEFAULT 'uyumsoft',
 document_type ENUM('unknown','efatura','earsiv') NOT NULL DEFAULT 'unknown',
 recipient_vkn_tckn VARCHAR(20) NOT NULL,
 recipient_alias VARCHAR(255) NULL,
 local_document_id VARCHAR(190) NOT NULL,
 profile_id VARCHAR(80) NOT NULL,
 ubl_xml MEDIUMTEXT NOT NULL,
 xml_sha256 CHAR(64) NOT NULL,
 external_uuid VARCHAR(190) NULL,
 external_number VARCHAR(190) NULL,
 external_scenario VARCHAR(80) NULL,
 status VARCHAR(40) NOT NULL DEFAULT 'prepared',
 status_code VARCHAR(40) NULL,
 last_error VARCHAR(1000) NULL,
 sent_at DATETIME NULL,
 checked_at DATETIME NULL,
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_edoc_order (order_id),
 UNIQUE KEY uq_edoc_local_id (local_document_id),
 INDEX idx_edoc_status (provider,status,created_at),
 INDEX idx_edoc_external_uuid (external_uuid),
 CONSTRAINT fk_edoc_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
