CREATE TABLE IF NOT EXISTS real_estate_listings (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 locale VARCHAR(5) NOT NULL DEFAULT 'tr',
 title VARCHAR(190) NOT NULL,
 slug VARCHAR(190) NOT NULL,
 listing_type ENUM('sale','rent') NOT NULL,
 property_type VARCHAR(80) NOT NULL,
 city VARCHAR(120) NOT NULL,
 district VARCHAR(120) NOT NULL,
 neighborhood VARCHAR(120) NULL,
 price DECIMAL(14,2) NOT NULL,
 currency CHAR(3) NOT NULL DEFAULT 'TRY',
 area_m2 DECIMAL(10,2) NOT NULL,
 rooms VARCHAR(30) NULL,
 floor VARCHAR(30) NULL,
 latitude DECIMAL(10,7) NULL,
 longitude DECIMAL(10,7) NULL,
 description MEDIUMTEXT NOT NULL,
 image_path VARCHAR(255) NULL,
 status ENUM('draft','published','sold','rented') NOT NULL DEFAULT 'draft',
 created_at DATETIME NOT NULL,
 updated_at DATETIME NOT NULL,
 UNIQUE KEY uq_real_estate_locale_slug (locale, slug),
 INDEX idx_real_estate_filters (status, listing_type, property_type, city, district),
 INDEX idx_real_estate_price (price),
 INDEX idx_real_estate_area (area_m2)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
