<?php
declare(strict_types=1);
namespace Arcates\Services;
use Arcates\Core\App;use Arcates\Core\Database;use Arcates\Einvoice\EinvoiceFactory;use Arcates\Einvoice\UblValidator;

final class EDocumentService
{
    public function prepare(int $orderId,string $ublXml,string $alias=''): int
    {
        $order=App::db()->fetch('SELECT * FROM orders WHERE id=?',[$orderId]);if(!$order)throw new \RuntimeException('Sipariş bulunamadı.');if((string)$order['payment_status']!=='paid'||(string)$order['status']==='cancelled')throw new \RuntimeException('e-Belge yalnız ödenmiş ve iptal edilmemiş sipariş için hazırlanabilir.');$id=self::identity((string)$order['identity_number']);$ins=UblValidator::inspect($ublXml,(int)App::config('integrations.einvoice.max_xml_bytes',2097152));$local=mb_substr('ARC-'.$order['public_code'],0,190);$alias=mb_substr(trim($alias),0,255);
        return App::db()->transaction(function(Database $db)use($orderId,$id,$ins,$local,$alias): int{$current=$db->fetch('SELECT * FROM e_documents WHERE order_id=? FOR UPDATE',[$orderId]);if($current&&!in_array((string)$current['status'],['prepared','failed'],true))throw new \RuntimeException('Gönderilmiş/işlemde e-Belge değiştirilemez.');if($current){$db->execute('UPDATE e_documents SET recipient_vkn_tckn=?,recipient_alias=?,profile_id=?,ubl_xml=?,xml_sha256=?,document_type=\'unknown\',external_uuid=NULL,external_number=NULL,external_scenario=NULL,status=\'prepared\',status_code=NULL,claim_token=NULL,claimed_at=NULL,last_error=NULL,sent_at=NULL,checked_at=NULL,updated_at=NOW() WHERE id=?',[$id,$alias!==''?$alias:null,$ins['profile_id'],$ins['xml'],$ins['sha256'],(int)$current['id']]);return (int)$current['id'];}$db->execute('INSERT INTO e_documents(order_id,provider,document_type,recipient_vkn_tckn,recipient_alias,local_document_id,profile_id,ubl_xml,xml_sha256,status,created_at,updated_at) VALUES(?,\'uyumsoft\',\'unknown\',?,?,?,?,?,?,\'prepared\',NOW(),NOW())',[$orderId,$id,$alias!==''?$alias:null,$local,$ins['profile_id'],$ins['xml'],$ins['sha256']]);return (int)$db->lastInsertId();});
    }
    public function send(int $documentId): array
    {
        $gateway=EinvoiceFactory::make();$claim=bin2hex(random_bytes(16));$row=App::db()->transaction(function(Database $db)use($documentId,$claim): array{$doc=$db->fetch('SELECT d.*,o.customer_name,o.email,o.public_code FROM e_documents d JOIN orders o ON o.id=d.order_id WHERE d.id=? FOR UPDATE',[$documentId]);if(!$doc)throw new \RuntimeException('e-Belge bulunamadı.');if(!in_array((string)$doc['status'],['prepared','failed'],true))throw new \RuntimeException('e-Belge zaten gönderilmiş veya işlemde.');if($doc['claimed_at']&&strtotime((string)$doc['claimed_at'])>time()-600)throw new \RuntimeException('e-Belge başka bir işlem tarafından gönderiliyor.');$db->execute('UPDATE e_documents SET claim_token=?,claimed_at=NOW(),status=\'sending\',last_error=NULL,updated_at=NOW() WHERE id=?',[$claim,$documentId]);return $doc;});
        try{$isUser=$gateway->isEInvoiceUser((string)$row['recipient_vkn_tckn'],(string)($row['recipient_alias']??''));$type=$isUser?'efatura':'earsiv';$profile=strtoupper((string)$row['profile_id']);if($type==='earsiv'&&$profile!=='EARSIVFATURA')throw new \RuntimeException('Alıcı e-Fatura mükellefi değil; UBL ProfileID EARSIVFATURA olmalı.');if($type==='efatura'&&$profile==='EARSIVFATURA')throw new \RuntimeException('Alıcı e-Fatura mükellefi; EARSIVFATURA profiliyle gönderilemez.');$result=$gateway->send((string)$row['ubl_xml'],['vkn_tckn'=>(string)$row['recipient_vkn_tckn'],'alias'=>(string)($row['recipient_alias']??''),'title'=>(string)$row['customer_name'],'email'=>(string)$row['email'],'local_document_id'=>(string)$row['local_document_id'],'document_type'=>$type]);App::db()->execute('UPDATE e_documents SET provider=?,document_type=?,external_uuid=?,external_number=?,external_scenario=?,status=\'submitted\',claim_token=NULL,claimed_at=NULL,last_error=NULL,sent_at=NOW(),updated_at=NOW() WHERE id=? AND claim_token=?',[$gateway->provider(),$type,mb_substr((string)$result['uuid'],0,190),mb_substr((string)($result['number']??''),0,190)?:null,mb_substr((string)($result['scenario']??''),0,80)?:null,$documentId,$claim]);return $result+['document_type'=>$type];}catch(\Throwable $e){App::db()->execute('UPDATE e_documents SET status=\'failed\',claim_token=NULL,claimed_at=NULL,last_error=?,updated_at=NOW() WHERE id=? AND claim_token=?',[mb_substr($e->getMessage(),0,1000),$documentId,$claim]);throw $e;}
    }
    public function checkPending(int $limit=20): array
    {
        $gateway=EinvoiceFactory::make();$rows=array_slice(App::db()->fetchAll('SELECT * FROM e_documents WHERE provider=? AND external_uuid IS NOT NULL AND status IN (\'submitted\',\'queued\',\'processing\',\'sent_to_gib\',\'waiting_approval\') ORDER BY id ASC',[$gateway->provider()]),0,max(1,min(100,$limit)));$summary=['checked'=>0,'approved'=>0,'failed'=>0,'processing'=>0];foreach($rows as $row){$summary['checked']++;try{$r=$gateway->status((string)$row['external_uuid']);$status=(string)($r['status']??'processing');App::db()->execute('UPDATE e_documents SET status=?,status_code=?,last_error=?,checked_at=NOW(),updated_at=NOW() WHERE id=?',[$status,mb_substr((string)($r['status_code']??''),0,40)?:null,$status==='failed'?mb_substr((string)($r['message']??'Entegratör hatası'),0,1000):null,(int)$row['id']]);$summary[$status]=($summary[$status]??0)+1;}catch(\Throwable $e){App::db()->execute('UPDATE e_documents SET last_error=?,checked_at=NOW(),updated_at=NOW() WHERE id=?',[mb_substr($e->getMessage(),0,1000),(int)$row['id']]);}}return $summary;
    }
    private static function identity(string $id): string{$id=preg_replace('/\D+/','',$id)??'';if(!in_array(strlen($id),[10,11],true))throw new \RuntimeException('Siparişte gerçek 10/11 haneli VKN/TCKN gerekli.');return $id;}
}
