<?php
return [
    'app' => [
        'name' => 'Arcates Core',
        'url' => 'http://localhost',
        'env' => 'production',
        'debug' => false,
        'timezone' => 'Europe/Istanbul',
        'session_name' => 'arcates_session',
        'admin_path' => 'yonetim',
        'default_locale' => 'tr',
        'supported_locales' => ['tr', 'en', 'de', 'ar'],
    ],
    'db' => [
        'host' => '127.0.0.1',
        'port' => 3306,
        'name' => 'arcates',
        'user' => 'arcates',
        'pass' => '',
        'charset' => 'utf8mb4',
    ],
    'mail' => [
        'from' => 'noreply@example.com',
        'to' => 'info@example.com',
    ],
    'contact' => [
        'whatsapp_phone' => '',
        'whatsapp_message' => 'Merhaba, bilgi almak istiyorum.',
    ],
    'security' => [
        'force_https' => true,
        'max_upload_bytes' => 5242880,
        'form_retention_days' => 180,
    ],
    'integrations' => [
        'payment_provider' => null,
        'payment_sdk_path' => __DIR__ . '/integrations/iyzipay/IyzipayBootstrap.php',
        'iyzico' => [
            'api_key' => '',
            'secret_key' => '',
            'base_url' => 'https://sandbox-api.iyzipay.com',
        ],
        'shipping' => [
            'provider' => null,
            'mng' => [
                'base_url' => 'https://api.mngkargo.com.tr',
                'client_id' => '',
                'client_secret' => '',
                'customer_number' => '',
                'password' => '',
                'identity_type' => 1,
                'create_barcode' => true,
            ],
            'aras' => [
                'wsdl' => 'https://customerservices.araskargo.com.tr/ArasCargoCustomerIntegrationService/ArasCargoIntegrationService.svc?wsdl',
                'barcode_wsdl' => 'https://customerws.araskargo.com.tr/arascargoservice.asmx?WSDL',
                'username' => '',
                'password' => '',
                'sender_account_address_id' => '',
            ],
            'yurtici' => [
                'wsdl' => 'https://ws.yurticikargo.com/KOPSWebServices/ShippingOrderDispatcherServices?wsdl',
                'username' => '',
                'password' => '',
                'language' => 'TR',
                'create_operation' => 'createShipment',
                'track_operation' => 'queryShipment',
                'label_operation' => 'createShipmentWithDelivery',
            ],
        ],
        'marketplace' => [
            'trendyol' => [
                'base_url' => 'https://apigw.trendyol.com',
                'seller_id' => '',
                'api_key' => '',
                'api_secret' => '',
                'storefront_code' => 'TR',
                'user_agent' => 'ArcatesCore/0.7',
            ],
            'hepsiburada' => [
                'base_url' => 'https://listing-external.hepsiburada.com',
                'merchant_id' => '',
                'username' => '',
                'password' => '',
                'user_agent' => 'ArcatesCore',
                'dispatch_time' => 2,
                'max_purchasable_quantity' => 1000,
            ],
        ],
        'einvoice' => [
            'provider' => 'uyumsoft',
            'max_xml_bytes' => 2097152,
            'uyumsoft' => [
                'wsdl' => 'http://efatura-test.uyumsoft.com.tr/Services/BasicIntegration?wsdl',
                'username' => '',
                'password' => '',
                'timeout' => 20,
                'send_operation' => 'SendInvoice',
                'status_operation' => 'QueryOutboxInvoiceStatus',
                'user_query_operation' => 'IsEInvoiceUser',
            ],
        ],
    ],
];
