<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];require_once $root.'/app/Accounting/TemplateRenderer.php';
$files=['app/Accounting/AccountingGateway.php','app/Accounting/AccountingFactory.php','app/Accounting/HttpTransport.php','app/Accounting/UncertainTransferException.php','app/Accounting/LogoNetsisGateway.php','app/Accounting/MikroGateway.php','app/Accounting/ParasutGateway.php','app/Accounting/TemplateRenderer.php','app/Services/AccountingExportService.php','app/Controllers/AccountingAdminController.php','db/migrations/20260906_015_accounting_exports.sql'];foreach($files as $f)if(!is_file($root.'/'.$f))$fail[]='Eksik: '.$f;
$template=['ref'=>'{{order.public_code}}','total'=>'{{order.grand_total}}','rows'=>['$each'=>'items','template'=>['sku'=>'{{item.sku}}','qty'=>'{{item.quantity}}','desc'=>'Satır {{item.name}}']]];$render=\Arcates\Accounting\TemplateRenderer::render($template,['public_code'=>'ARC-1','grand_total'=>'125.50'],[['sku'=>'SKU1','quantity'=>2,'name'=>'Ürün']]);if(($render['ref']??'')!=='ARC-1'||($render['rows'][0]['sku']??'')!=='SKU1'||($render['rows'][0]['qty']??null)!==2)$fail[]='Muhasebe şablon render sonucu hatalı.';$renderer=(string)@file_get_contents($root.'/app/Accounting/TemplateRenderer.php');if(str_contains(strtolower($renderer),'eval('))$fail[]='Muhasebe şablon motoru eval kullanamaz.';
$logo=(string)@file_get_contents($root.'/app/Accounting/LogoNetsisGateway.php');foreach(['/api/v2/GLSlips','Authorization: Bearer','Content-Type: application/json'] as $n)if(!str_contains($logo,$n))$fail[]='Logo NetOpenX sözleşmesi eksik: '.$n;
$mikro=(string)@file_get_contents($root.'/app/Accounting/MikroGateway.php');foreach(['/Api/apiMethods/MuhasebeFisKaydetV2','ApiKey','CalismaYili','FirmaKodu','KullaniciKodu','Sifre','evraklar'] as $n)if(!str_contains($mikro,$n))$fail[]='Mikro API sözleşmesi eksik: '.$n;
$parasut=(string)@file_get_contents($root.'/app/Accounting/ParasutGateway.php');foreach(['api.parasut.com/oauth/token','grant_type','password','sales_invoices','application/vnd.api+json','Authorization: Bearer'] as $n)if(!str_contains($parasut,$n))$fail[]='Paraşüt API sözleşmesi eksik: '.$n;
$service=(string)@file_get_contents($root.'/app/Services/AccountingExportService.php');foreach(["payment_status']!=='paid'",'accounting_profiles','payload_sha256','claim_token','send_unknown','UncertainTransferException','reconcile','resetUnknown'] as $n)if(!str_contains($service,$n))$fail[]='Muhasebe iş kuralı eksik: '.$n;if(str_contains(strtolower($service),'vat_rate')||str_contains(strtolower($service),'kdv'))$fail[]='Muhasebe aktarım servisi vergi oranı hesaplamamalı.';
$admin=(string)@file_get_contents($root.'/app/Controllers/AccountingAdminController.php');foreach(['AdminView::requireUser','Csrf::requireValid','template_json','confirmed_absent','reconcile','resetUnknown'] as $n)if(!str_contains($admin,$n))$fail[]='Muhasebe admin güvenliği eksik: '.$n;
$migration=(string)@file_get_contents($root.'/db/migrations/20260906_015_accounting_exports.sql');foreach(['accounting_profiles','accounting_exports','payload_sha256','send_unknown','UNIQUE KEY uq_accounting_export','claim_token'] as $n)if(!str_contains($migration,$n))$fail[]='Muhasebe veri modeli eksik: '.$n;
$config=(string)@file_get_contents($root.'/config.example.php');$pos=(int)strpos($config,"'accounting' =>");$section=$pos>0?substr($config,$pos):'';foreach(["'access_token' => ''","'api_key' => ''","'client_secret' => ''","'password' => ''"] as $n)if(!str_contains($section,$n))$fail[]='Muhasebe credential örneği boş değil/eksik: '.$n;
$router=(string)@file_get_contents($root.'/public/index.php');foreach(['/muhasebe/profil','/muhasebe/hazirla','/muhasebe/gonder','/muhasebe/uzlastir','/muhasebe/sifirla'] as $n)if(!str_contains($router,$n))$fail[]='Muhasebe route eksik: '.$n;
if($fail){fwrite(STDERR,implode(PHP_EOL,$fail).PHP_EOL);exit(1);}echo "Muhasebe aktarım testleri: OK\n";
