<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];$files=['app/AI/OpenAIResponsesClient.php','app/Services/SiteAssistantService.php','app/Controllers/AssistantController.php','app/Core/AssistantWidget.php','public/assets/js/assistant.js'];foreach($files as $f)if(!is_file($root.'/'.$f))$fail[]='Eksik: '.$f;
$client=(string)@file_get_contents($root.'/app/AI/OpenAIResponsesClient.php');foreach(['/responses','Authorization: Bearer',"'store'=>false",'max_output_tokens','gpt-5.6-luna','CURLOPT_TIMEOUT'] as $n)if(!str_contains($client,$n))$fail[]='AI Responses sözleşmesi eksik: '.$n;if(str_contains($client,'previous_response_id')||str_contains($client,"'tools'"))$fail[]='Site asistanı konuşma zinciri veya araç erişimi kullanmamalı.';
$service=(string)@file_get_contents($root.'/app/Services/SiteAssistantService.php');foreach(["status='published'","is_active=1",'site_content','untrusted data','Never invent prices','context_chars'] as $n)if(!str_contains($service,$n))$fail[]='AI grounding kuralı eksik: '.$n;if(!preg_match('/mb_strlen\(\$question\)\s*>\s*1000/',$service))$fail[]='AI soru uzunluk sınırı (1000) eksik.';// Ziyaretçi sorusu ile site içeriği yapısal olarak ayrılmalı; sınırlayıcı taklidiyle sahte içerik enjekte edilememeli.
foreach(['visitor_question','json_encode'] as $n)if(!str_contains($service,$n))$fail[]='AI istem enjeksiyonu koruması eksik: '.$n;foreach(['orders','users','contact_submissions','newsletter_subscribers','reservations'] as $n)if(str_contains($service,'FROM '.$n)||str_contains($service,'JOIN '.$n))$fail[]='AI bağlamı özel/işlemsel tabloya erişmemeli: '.$n;
$controller=(string)@file_get_contents($root.'/app/Controllers/AssistantController.php');foreach(['Csrf::requireValid','genericAllowed','Content-Type: application/json','SiteAssistantService'] as $n)if(!str_contains($controller,$n))$fail[]='AI endpoint güvenliği eksik: '.$n;if(!preg_match('/genericAllowed\([^)]*,\s*12\s*,\s*300\s*\)/',$controller))$fail[]='AI hız limiti 12/300 sn olmalı.';// Hız limiti kovası IP ile anahtarlanmalı; aksi halde çerez atarak atlatılır.
if(!str_contains($controller,'Security::clientIp()'))$fail[]='AI hız limiti IP ile anahtarlanmıyor.';
$widget=(string)@file_get_contents($root.'/app/Core/AssistantWidget.php');foreach(["integrations.ai.enabled",'Csrf::token','tr','en','de','ar'] as $n)if(!str_contains($widget,$n))$fail[]='AI widget sözleşmesi eksik: '.$n;
$js=(string)@file_get_contents($root.'/public/assets/js/assistant.js');foreach(['textContent','/asistan/sor','URLSearchParams',"credentials:'same-origin'"] as $n)if(!str_contains($js,$n))$fail[]='AI istemci güvenliği eksik: '.$n;if(str_contains($js,'innerHTML'))$fail[]='AI istemcisi innerHTML kullanmamalı.';
$config=(string)@file_get_contents($root.'/config.example.php');foreach(["'enabled' => false","'api_key' => ''","'model' => 'gpt-5.6-luna'",'https://api.openai.com/v1'] as $n)if(!str_contains($config,$n))$fail[]='AI config örneği eksik: '.$n;
$router=(string)@file_get_contents($root.'/public/index.php');if(!str_contains($router,"post('/asistan/sor'"))$fail[]='AI POST route eksik.';if(str_contains($router,"get('/asistan/sor'"))$fail[]='AI soru endpointi GET olmamalı.';
if(glob($root.'/db/migrations/*assistant*')||glob($root.'/db/migrations/*ai_*'))$fail[]='AI konuşmaları için kalıcı migration oluşturulmamalı.';
if($fail){fwrite(STDERR,implode(PHP_EOL,$fail).PHP_EOL);exit(1);}echo "AI asistan testleri: OK\n";
