<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
foreach(['app/Shipping/CarrierGateway.php','app/Shipping/CarrierFactory.php','app/Shipping/MngGateway.php','app/Shipping/ArasGateway.php','app/Shipping/YurticiGateway.php','app/Controllers/CarrierAdminController.php','db/migrations/20260906_011_carrier_integrations.sql'] as $f){if(!is_file($root.'/'.$f))$fail[]='Eksik: '.$f;}
$mng=(string)@file_get_contents($root.'/app/Shipping/MngGateway.php');foreach(['/mngapi/api/token','/standardcmdapi/createOrder','/standardqueryapi/getshipmentstatus/','/standardqueryapi/trackshipment/','/barcodecmdapi/createbarcode','X-IBM-Client-Id','X-IBM-Client-Secret','Authorization: Bearer','curl_init','FILTER_VALIDATE_EMAIL'] as $needle){if(!str_contains($mng,$needle))$fail[]='MNG adapter kuralı eksik: '.$needle;}foreach(['11111111110','11111111111','CLIENT_SECRET_HERE','PASSWORD_HERE'] as $forbidden){if(str_contains($mng,$forbidden))$fail[]='MNG adapterinde sahte/gerçek dışı credential bulundu: '.$forbidden;}
$aras=(string)@file_get_contents($root.'/app/Shipping/ArasGateway.php');foreach(['SoapClient','SetOrder','GetCargoTransaction','GetArasBarcode','ReceiverTownName','IntegrationCode'] as $needle){if(!str_contains($aras,$needle))$fail[]='Aras SOAP kuralı eksik: '.$needle;}
$yk=(string)@file_get_contents($root.'/app/Shipping/YurticiGateway.php');foreach(['SoapClient','ShippingOrderVO','createShipment','queryShipment','createShipmentWithDelivery','cargoKey','invoiceKey','receiverCustName','townName'] as $needle){if(!str_contains($yk,$needle))$fail[]='Yurtiçi KOPS kuralı eksik: '.$needle;}
$admin=(string)@file_get_contents($root.'/app/Controllers/CarrierAdminController.php');foreach(['Csrf::requireValid','CarrierFactory::supported','CarrierFactory::make','carrier_shipments','weight_kg','desi','package_count'] as $needle){if(!str_contains($admin,$needle))$fail[]='Kargo admin güvenliği eksik: '.$needle;}
$config=(string)@file_get_contents($root.'/config.example.php');foreach(["'mng' => [","'aras' => [","'yurtici' => [","'client_id' => ''","'username' => ''","'password' => ''"] as $needle){if(!str_contains($config,$needle))$fail[]='Kargo config örneği eksik: '.$needle;}
$migration=(string)@file_get_contents($root.'/db/migrations/20260906_011_carrier_integrations.sql');foreach(['carrier_shipments',"ENUM('mng','aras','yurtici')",'recipient_district','weight_kg','desi','FOREIGN KEY','ON DELETE CASCADE'] as $needle){if(!str_contains($migration,$needle))$fail[]='Kargo veri modeli eksik: '.$needle;}
$router=(string)@file_get_contents($root.'/public/index.php');foreach(['/kargo-entegrasyon/olustur','/kargo-entegrasyon/takip','/kargo-entegrasyon/etiket'] as $needle){if(!str_contains($router,$needle))$fail[]='Kargo route eksik: '.$needle;}
if(!extension_loaded('curl'))$fail[]='CI/runtime curl eklentisi yok.';if(!extension_loaded('soap'))$fail[]='CI/runtime soap eklentisi yok.';
if($fail){fwrite(STDERR,implode(PHP_EOL,$fail).PHP_EOL);exit(1);}echo "Kargo entegrasyon testleri: OK\n";
