<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];require_once $root.'/app/Einvoice/UblValidator.php';
$files=['app/Einvoice/EinvoiceGateway.php','app/Einvoice/EinvoiceFactory.php','app/Einvoice/UyumsoftGateway.php','app/Einvoice/UblValidator.php','app/Services/EDocumentService.php','app/Controllers/EDocumentAdminController.php','db/migrations/20260906_014_e_documents.sql','scripts/edocument_status.php'];foreach($files as $f)if(!is_file($root.'/'.$f))$fail[]='Eksik: '.$f;
$valid='<?xml version="1.0" encoding="UTF-8"?><Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"><cbc:ProfileID>EARSIVFATURA</cbc:ProfileID><cbc:DocumentCurrencyCode>TRY</cbc:DocumentCurrencyCode></Invoice>';try{$i=\Arcates\Einvoice\UblValidator::inspect($valid);if(($i['profile_id']??'')!=='EARSIVFATURA'||($i['currency']??'')!=='TRY'||strlen((string)($i['sha256']??''))!==64)$fail[]='UBL doğrulama sonucu hatalı.';}catch(Throwable $e){$fail[]='Geçerli UBL reddedildi: '.$e->getMessage();}
$evil='<!DOCTYPE Invoice [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"><ProfileID>&xxe;</ProfileID></Invoice>';$rejected=false;try{\Arcates\Einvoice\UblValidator::inspect($evil);}catch(Throwable){$rejected=true;}if(!$rejected)$fail[]='DTD/ENTITY UBL reddedilmeli.';
$gw=(string)@file_get_contents($root.'/app/Einvoice/UyumsoftGateway.php');foreach(['SendInvoice','QueryOutboxInvoiceStatus','IsEInvoiceUser','userInfo','XSD_ANYXML','SoapClient','StatusCode'] as $n)if(!str_contains($gw,$n))$fail[]='Uyumsoft sözleşmesi eksik: '.$n;
$service=(string)@file_get_contents($root.'/app/Services/EDocumentService.php');foreach(["payment_status']!=='paid'",'identity_number','claim_token','isEInvoiceUser','EARSIVFATURA','checkPending','external_uuid','send_unknown','attachExternal','resetUnknown','LocalDocumentId'] as $n)if(!str_contains($service,$n)&&$n!=='LocalDocumentId')$fail[]='e-Belge iş kuralı eksik: '.$n;if(!str_contains($gw,'LocalDocumentId'))$fail[]='Uyumsoft LocalDocumentId idempotency referansı eksik.';if(str_contains(strtolower($service),'vat_rate')||str_contains(strtolower($service),'kdv'))$fail[]='e-Belge modülü yasal vergi oranı hesaplamamalı.';
$admin=(string)@file_get_contents($root.'/app/Controllers/EDocumentAdminController.php');foreach(['AdminView::requireUser','Csrf::requireValid','ubl_xml','prepare(','send(','checkPending','reconcile','resetUnknown','confirmed_absent'] as $n)if(!str_contains($admin,$n))$fail[]='e-Belge admin güvenliği eksik: '.$n;
$migration=(string)@file_get_contents($root.'/db/migrations/20260906_014_e_documents.sql');foreach(['e_documents','ubl_xml MEDIUMTEXT','xml_sha256','external_uuid','document_type','claim_token','UNIQUE KEY uq_edoc_order'] as $n)if(!str_contains($migration,$n))$fail[]='e-Belge veri modeli eksik: '.$n;
$config=(string)@file_get_contents($root.'/config.example.php');foreach(['efatura-test.uyumsoft.com.tr/Services/BasicIntegration?wsdl','SendInvoice','QueryOutboxInvoiceStatus','IsEInvoiceUser'] as $n)if(!str_contains($config,$n))$fail[]='Uyumsoft config eksik: '.$n;if(preg_match("/'(?:username|password)'\s*=>\s*'[^']+'/",substr($config,(int)strpos($config,"'einvoice' =>"))))$fail[]='e-Belge credential örneği boş olmalı.';
$router=(string)@file_get_contents($root.'/public/index.php');foreach(['/e-belge/hazirla','/e-belge/gonder','/e-belge/kontrol','/e-belge/uzlastir','/e-belge/sifirla'] as $n)if(!str_contains($router,$n))$fail[]='e-Belge route eksik: '.$n;
if($fail){fwrite(STDERR,implode(PHP_EOL,$fail).PHP_EOL);exit(1);}echo "e-Belge testleri: OK\n";
