<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];
$files=['app/Marketplace/MarketplaceGateway.php','app/Marketplace/MarketplaceFactory.php','app/Marketplace/TrendyolGateway.php','app/Marketplace/HepsiburadaGateway.php','app/Services/MarketplaceSyncService.php','app/Controllers/MarketplaceAdminController.php','db/migrations/20260906_013_marketplace_sync.sql','scripts/marketplace_sync.php'];foreach($files as $f)if(!is_file($root.'/'.$f))$fail[]='Eksik: '.$f;
$tr=(string)@file_get_contents($root.'/app/Marketplace/TrendyolGateway.php');foreach(['maxBatchSize(): int{return 1000','price-and-inventory','batch-requests','storeFrontCode','Authorization: Basic','listPrice','salePrice','quantity'] as $n)if(!str_contains($tr,$n))$fail[]='Trendyol sözleşmesi eksik: '.$n;if(str_contains($tr,'CURLOPT_POSTFIELDS')&&!str_contains($tr,'JSON_THROW_ON_ERROR'))$fail[]='Trendyol JSON güvenli encode eksik.';
$hb=(string)@file_get_contents($root.'/app/Marketplace/HepsiburadaGateway.php');foreach(['maxBatchSize(): int{return 4000','inventory-uploads','HepsiburadaSku','MerchantSku','AvailableStock','Authorization: Basic','User-Agent:'] as $n)if(!str_contains($hb,$n))$fail[]='Hepsiburada sözleşmesi eksik: '.$n;
$sync=(string)@file_get_contents($root.'/app/Services/MarketplaceSyncService.php');foreach(['payload_hash','last_payload_hash','pending_payload_hash','claim_token','FOR UPDATE','>=5','checkPending','guardQueue'] as $n)if(!str_contains($sync,$n))$fail[]='Senkron koruması eksik: '.$n;if(preg_match('/transaction\([^)]*gateway->/s',$sync))$fail[]='Dış API çağrısı DB transaction içinde olmamalı.';
$admin=(string)@file_get_contents($root.'/app/Controllers/MarketplaceAdminController.php');foreach(['Csrf::requireValid','AdminView::requireUser','trendyol','hepsiburada','price_multiplier','stock_reserve'] as $n)if(!str_contains($admin,$n))$fail[]='Pazaryeri admin kuralı eksik: '.$n;
$migration=(string)@file_get_contents($root.'/db/migrations/20260906_013_marketplace_sync.sql');foreach(['marketplace_mappings','marketplace_batches','marketplace_batch_items','UNIQUE KEY uq_marketplace_mapping','claim_token','payload_hash'] as $n)if(!str_contains($migration,$n))$fail[]='Pazaryeri veri modeli eksik: '.$n;
$config=(string)@file_get_contents($root.'/config.example.php');foreach(['apigw.trendyol.com','listing-external.hepsiburada.com','seller_id','merchant_id','api_key','api_secret','username','password'] as $n)if(!str_contains($config,$n))$fail[]='Pazaryeri config örneği eksik: '.$n;if(preg_match("/'(?:api_key|api_secret|username|password)'\s*=>\s*'[^']+'/",$config))$fail[]='Pazaryeri credential örneği boş olmalı.';
$router=(string)@file_get_contents($root.'/public/index.php');foreach(['/pazaryeri/esle','/pazaryeri/senkron','/pazaryeri/kontrol'] as $n)if(!str_contains($router,$n))$fail[]='Pazaryeri route eksik: '.$n;
if($fail){fwrite(STDERR,implode(PHP_EOL,$fail).PHP_EOL);exit(1);}echo "Pazaryeri testleri: OK\n";
