<?php
declare(strict_types=1);
$root=dirname(__DIR__);$fail=[];$files=['app/Services/NewsletterService.php','app/Controllers/NewsletterController.php','app/Controllers/NewsletterAdminController.php','scripts/newsletter_send.php','db/migrations/20260906_017_newsletter.sql'];foreach($files as $f)if(!is_file($root.'/'.$f))$fail[]='Eksik: '.$f;
$service=(string)@file_get_contents($root.'/app/Services/NewsletterService.php');foreach(['random_bytes(32)','hash(\'sha256\'','48 HOUR','hash_hmac','hash_equals','newsletter.secret','status=\'unsubscribed\'','status=\'active\'','sendBatch','attempts<3','subscriber_status'] as $n)if(!str_contains($service,$n))$fail[]='Bülten güvenlik/iş kuralı eksik: '.$n;foreach(['REMOTE_ADDR','unsubscribe_token VARCHAR','confirm_token VARCHAR'] as $n)if(str_contains($service,$n))$fail[]='Bülten düz token/IP saklayamaz: '.$n;
$public=(string)@file_get_contents($root.'/app/Controllers/NewsletterController.php');foreach(['Csrf::requireValid','website','RateLimiter','Security::clientIp','consent','NewsletterService','confirm','unsubscribe'] as $n)if(!str_contains($public,$n))$fail[]='Public bülten güvenliği eksik: '.$n;
$adminCode=(string)@file_get_contents($root.'/app/Controllers/NewsletterAdminController.php');foreach(['AdminView::requireUser','Csrf::requireValid','body_text','queue'] as $n)if(!str_contains($adminCode,$n))$fail[]='Bülten admin güvenliği eksik: '.$n;
$m=(string)@file_get_contents($root.'/db/migrations/20260906_017_newsletter.sql');foreach(['newsletter_subscribers','confirm_token_hash CHAR(64)','newsletter_campaigns','newsletter_deliveries','UNIQUE KEY uq_newsletter_email','status ENUM(\'pending\',\'active\',\'unsubscribed\')'] as $n)if(!str_contains($m,$n))$fail[]='Bülten veri modeli eksik: '.$n;if(str_contains($m,'ip_address')||str_contains($m,'unsubscribe_token VARCHAR'))$fail[]='Bülten IP veya düz unsubscribe token saklayamaz.';
$mail=(string)@file_get_contents($root.'/app/Services/Mailer.php');foreach(['newsletterConfirmation','newsletter(','abonelikten ayrılın'] as $n)if(!str_contains($mail,$n))$fail[]='Bülten Mailer desteği eksik: '.$n;
$config=(string)@file_get_contents($root.'/config.example.php');if(!str_contains($config,"'newsletter' =>")||!str_contains($config,"'secret' => ''")||!str_contains($config,"'send_batch' => 50"))$fail[]='Bülten config örneği eksik veya secret dolu.';
$router=(string)@file_get_contents($root.'/public/index.php');foreach(["'/bulten'","'/bulten/onay'","'/bulten/ayril'",'NewsletterAdminController::class'] as $n)if(!str_contains($router,$n))$fail[]='Bülten route eksik: '.$n;
if($fail){fwrite(STDERR,implode(PHP_EOL,$fail).PHP_EOL);exit(1);}echo "Bülten testleri: OK\n";
