<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use Arcates\Controllers\AdminController;use Arcates\Controllers\AuthController;use Arcates\Controllers\B2BAdminController;use Arcates\Controllers\B2BController;use Arcates\Controllers\BlogAdminController;use Arcates\Controllers\BlogController;use Arcates\Controllers\CartController;use Arcates\Controllers\CatalogController;use Arcates\Controllers\CheckoutController;use Arcates\Controllers\ContactController;use Arcates\Controllers\GalleryAdminController;use Arcates\Controllers\GalleryController;use Arcates\Controllers\HomeController;use Arcates\Controllers\IcalController;use Arcates\Controllers\InstallController;use Arcates\Controllers\LeadAdminController;use Arcates\Controllers\LegalController;use Arcates\Controllers\MediaController;use Arcates\Controllers\MenuController;use Arcates\Controllers\OrderAdminController;use Arcates\Controllers\PageAdminController;use Arcates\Controllers\PaymentController;use Arcates\Controllers\ProductAdminController;use Arcates\Controllers\PublicPageController;use Arcates\Controllers\ReservationAdminController;use Arcates\Controllers\ReservationController;use Arcates\Controllers\SeoController;use Arcates\Controllers\ShippingAdminController;use Arcates\Controllers\TestimonialAdminController;use Arcates\Controllers\TestimonialController;use Arcates\Core\Router;
$router=new Router();$admin=trim((string)($GLOBALS['arcates_config']['app']['admin_path']??'yonetim'),'/');
$router->get('/',[HomeController::class,'index']);$router->get('/install',[InstallController::class,'form']);$router->post('/install',[InstallController::class,'install']);
$router->get('/sitemap.xml',[SeoController::class,'sitemap']);$router->get('/robots.txt',[SeoController::class,'robots']);
$router->get('/iletisim',[ContactController::class,'form']);$router->post('/iletisim',[ContactController::class,'submit']);$router->get('/kvkk',[LegalController::class,'kvkk']);$router->get('/gizlilik',[LegalController::class,'privacy']);$router->get('/mesafeli-satis',[LegalController::class,'distanceSales']);$router->get('/iade',[LegalController::class,'returns']);$router->get('/portfoy',[GalleryController::class,'index']);$router->get('/referanslar',[TestimonialController::class,'index']);$router->get('/rezervasyon',[ReservationController::class,'form']);$router->post('/rezervasyon',[ReservationController::class,'submit']);$router->get('/rezervasyon/musaitlik',[ReservationController::class,'availability']);$router->get('/rezervasyon/ical',[IcalController::class,'export']);$router->get('/blog/{locale}',[BlogController::class,'index']);$router->get('/blog/{locale}/{slug}',[BlogController::class,'show']);
$router->get('/urunler/{locale}',[CatalogController::class,'index']);$router->get('/urun/{locale}/{slug}',[CatalogController::class,'show']);$router->get('/sepet',[CartController::class,'index']);$router->post('/sepet/ekle',[CartController::class,'add']);$router->post('/sepet/guncelle',[CartController::class,'update']);$router->get('/odeme',[CheckoutController::class,'form']);$router->post('/odeme',[CheckoutController::class,'submit']);$router->get('/odeme/baslat',[PaymentController::class,'start']);$router->get('/odeme/sonuc',[PaymentController::class,'callback']);$router->post('/odeme/sonuc',[PaymentController::class,'callback']);
$router->get('/bayi/giris',[B2BController::class,'loginForm']);$router->post('/bayi/giris',[B2BController::class,'login']);$router->get('/bayi/fiyat-listesi',[B2BController::class,'priceList']);$router->get('/bayi/fiyat-listesi.pdf',[B2BController::class,'pdf']);
$router->get('/'.$admin.'/giris',[AuthController::class,'form']);$router->post('/'.$admin.'/giris',[AuthController::class,'login']);$router->get('/'.$admin,[AdminController::class,'index']);$router->post('/'.$admin.'/cikis',[AuthController::class,'logout']);
$router->get('/'.$admin.'/sayfalar',[PageAdminController::class,'index']);$router->get('/'.$admin.'/sayfalar/yeni',[PageAdminController::class,'createForm']);$router->get('/'.$admin.'/sayfalar/duzenle',[PageAdminController::class,'editForm']);$router->post('/'.$admin.'/sayfalar/kaydet',[PageAdminController::class,'save']);$router->post('/'.$admin.'/sayfalar/sil',[PageAdminController::class,'delete']);
$router->get('/'.$admin.'/medya',[MediaController::class,'index']);$router->post('/'.$admin.'/medya',[MediaController::class,'upload']);$router->get('/'.$admin.'/menuler',[MenuController::class,'index']);$router->post('/'.$admin.'/menuler',[MenuController::class,'add']);$router->post('/'.$admin.'/menuler/sil',[MenuController::class,'delete']);
$router->get('/'.$admin.'/formlar',[LeadAdminController::class,'index']);$router->get('/'.$admin.'/portfoy',[GalleryAdminController::class,'index']);$router->post('/'.$admin.'/portfoy/kategori',[GalleryAdminController::class,'addCategory']);$router->post('/'.$admin.'/portfoy/ekle',[GalleryAdminController::class,'addItem']);$router->post('/'.$admin.'/portfoy/sil',[GalleryAdminController::class,'delete']);
$router->get('/'.$admin.'/blog',[BlogAdminController::class,'index']);$router->get('/'.$admin.'/blog/yeni',[BlogAdminController::class,'createForm']);$router->get('/'.$admin.'/blog/duzenle',[BlogAdminController::class,'editForm']);$router->post('/'.$admin.'/blog/kaydet',[BlogAdminController::class,'save']);$router->post('/'.$admin.'/blog/sil',[BlogAdminController::class,'delete']);
$router->get('/'.$admin.'/referanslar',[TestimonialAdminController::class,'index']);$router->post('/'.$admin.'/referanslar/ekle',[TestimonialAdminController::class,'add']);$router->post('/'.$admin.'/referanslar/sil',[TestimonialAdminController::class,'delete']);$router->get('/'.$admin.'/rezervasyon',[ReservationAdminController::class,'index']);$router->post('/'.$admin.'/rezervasyon/birim',[ReservationAdminController::class,'addUnit']);$router->post('/'.$admin.'/rezervasyon/sezon',[ReservationAdminController::class,'addSeason']);$router->post('/'.$admin.'/rezervasyon/durum',[ReservationAdminController::class,'status']);
$router->get('/'.$admin.'/urunler',[ProductAdminController::class,'index']);$router->post('/'.$admin.'/urunler/ekle',[ProductAdminController::class,'add']);$router->post('/'.$admin.'/urunler/varyant',[ProductAdminController::class,'addVariant']);$router->get('/'.$admin.'/siparisler',[OrderAdminController::class,'index']);$router->post('/'.$admin.'/siparisler/durum',[OrderAdminController::class,'status']);$router->get('/'.$admin.'/kargo',[ShippingAdminController::class,'index']);$router->post('/'.$admin.'/kargo/ekle',[ShippingAdminController::class,'addRule']);$router->post('/'.$admin.'/kupon/ekle',[ShippingAdminController::class,'addCoupon']);$router->get('/'.$admin.'/bayiler',[B2BAdminController::class,'index']);$router->post('/'.$admin.'/bayiler/ekle',[B2BAdminController::class,'add']);
$router->get('/{locale}/{slug}',[PublicPageController::class,'show']);$router->dispatch($_SERVER['REQUEST_METHOD']??'GET',$_SERVER['REQUEST_URI']??'/');
