<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\AdminView;use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Security;use Arcates\Services\AccountingExportService;

final class AccountingAdminController
{
    public function index(): void
    {
        AdminView::header('Muhasebe Aktarımı');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<section class="card"><h2>Aktarım profili</h2><p>Hesap/cari/kategori kodlarını kendi Logo, Mikro veya Paraşüt kurulumunuza göre JSON şablonunda tanımlayın. Desteklenen alanlar: {{order.public_code}}, {{order.grand_total}}, {{item.sku}} ve $each=items.</p><form method="post" action="/'.$a.'/muhasebe/profil">'.Csrf::field().'<input name="name" required maxlength="190" placeholder="Profil adı"><select name="provider"><option value="logo">Logo / Netsis</option><option value="mikro">Mikro</option><option value="parasut">Paraşüt</option></select><textarea name="template_json" required rows="14" maxlength="131072" placeholder="JSON şablonu"></textarea><button>Profili kaydet</button></form></section>';
        $profiles=App::db()->fetchAll('SELECT * FROM accounting_profiles WHERE is_active=1 ORDER BY provider,name');$orders=App::db()->fetchAll('SELECT id,public_code,customer_name,grand_total FROM orders WHERE payment_status=\'paid\' AND status<>\'cancelled\' ORDER BY id DESC LIMIT 100');echo '<section class="card"><h2>Aktarım hazırla</h2><form method="post" action="/'.$a.'/muhasebe/hazirla">'.Csrf::field().'<select name="order_id" required>';foreach($orders as $o)echo '<option value="'.(int)$o['id'].'">'.Security::escape($o['public_code'].' · '.$o['customer_name'].' · '.$o['grand_total']).'</option>';echo '</select><select name="profile_id" required>';foreach($profiles as $p)echo '<option value="'.(int)$p['id'].'">'.Security::escape(strtoupper($p['provider']).' · '.$p['name']).'</option>';echo '</select><button>Aktarımı hazırla</button></form></section>';
        foreach(App::db()->fetchAll('SELECT x.*,o.public_code,p.name profile_name FROM accounting_exports x JOIN orders o ON o.id=x.order_id JOIN accounting_profiles p ON p.id=x.profile_id ORDER BY x.id DESC LIMIT 100') as $x){echo '<article class="card"><strong>'.Security::escape(strtoupper($x['provider']).' · '.$x['public_code'].' · '.$x['profile_name']).'</strong><p>Durum: '.Security::escape($x['status']).' · Dış ID: '.Security::escape((string)($x['external_id']??'-')).'</p>'.($x['last_error']?'<p>Hata: '.Security::escape($x['last_error']).'</p>':'');if(in_array((string)$x['status'],['prepared','failed'],true))echo '<form method="post" action="/'.$a.'/muhasebe/gonder">'.Csrf::field().'<input type="hidden" name="id" value="'.(int)$x['id'].'"><button>Gönder</button></form>';if((string)$x['status']==='send_unknown')echo '<form method="post" action="/'.$a.'/muhasebe/uzlastir">'.Csrf::field().'<input type="hidden" name="id" value="'.(int)$x['id'].'"><input name="external_id" required placeholder="Dış sistem kayıt ID"><button>Dış kayıtla uzlaştır</button></form><form method="post" action="/'.$a.'/muhasebe/sifirla">'.Csrf::field().'<input type="hidden" name="id" value="'.(int)$x['id'].'"><label><input type="checkbox" name="confirmed_absent" value="1" required> Dış sistemde kayıt olmadığını doğruladım</label><button>Tekrar gönderime aç</button></form>';echo '</article>';}AdminView::footer();
    }
    public function profile(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$name=trim((string)($_POST['name']??''));$provider=(string)($_POST['provider']??'');$json=trim((string)($_POST['template_json']??''));if($name===''||!in_array($provider,['logo','mikro','parasut'],true)||$json===''||strlen($json)>131072)throw new \RuntimeException('Muhasebe profili geçersiz.');$data=json_decode($json,true,128,JSON_THROW_ON_ERROR);if(!is_array($data))throw new \RuntimeException('Profil şablonu JSON nesnesi olmalı.');App::db()->execute('INSERT INTO accounting_profiles(name,provider,template_json,is_active,created_at,updated_at) VALUES(?,?,?,1,NOW(),NOW()) ON DUPLICATE KEY UPDATE template_json=VALUES(template_json),is_active=1,updated_at=NOW()',[$name,$provider,json_encode($data,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR)]);$this->back();}
    public function prepare(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);(new AccountingExportService())->prepare((int)($_POST['order_id']??0),(int)($_POST['profile_id']??0));$this->back();}
    public function send(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);(new AccountingExportService())->send((int)($_POST['id']??0));$this->back();}
    public function reconcile(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);(new AccountingExportService())->reconcile((int)($_POST['id']??0),(string)($_POST['external_id']??''));$this->back();}
    public function reset(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);(new AccountingExportService())->resetUnknown((int)($_POST['id']??0),($_POST['confirmed_absent']??'')==='1');$this->back();}
    private function back(): void{header('Location: /'.App::config('app.admin_path','yonetim').'/muhasebe');}
}
