<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Security;use Arcates\Services\PdfPriceList;
final class B2BController
{
    public function loginForm(): void{echo '<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bayi girişi</title><link rel="stylesheet" href="/assets/css/theme.css"><body><main class="container"><h1>Bayi girişi</h1><form class="card" method="post">'.Csrf::field().'<label>E-posta<input type="email" name="email" required></label><label>Şifre<input type="password" name="password" required></label><button>Giriş</button></form></main></body></html>';}
    public function login(): void{Csrf::requireValid($_POST['_csrf']??null);$email=mb_strtolower(trim((string)($_POST['email']??'')));$row=App::db()->fetch('SELECT * FROM b2b_accounts WHERE email=? AND is_active=1',[$email]);if(!$row||!password_verify((string)($_POST['password']??''),(string)$row['password_hash']))throw new \RuntimeException('Giriş başarısız.');session_regenerate_id(true);$_SESSION['b2b_id']=(int)$row['id'];header('Location: /bayi/fiyat-listesi');}
    public function priceList(): void{$account=$this->account();$rows=$this->rows();echo '<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bayi fiyat listesi</title><link rel="stylesheet" href="/assets/css/theme.css"><body><main class="container"><h1>'.Security::escape($account['company_name']).' fiyat listesi</h1><p>İskonto: %'.Security::escape((string)$account['discount_percent']).' · <a href="/bayi/fiyat-listesi.pdf">PDF indir</a></p>';foreach($rows as $r){$price=(float)$r['price']*(1-(float)$account['discount_percent']/100);echo '<p>'.Security::escape($r['sku'].' · '.$r['product_name'].' - '.$r['variant_name']).' · '.number_format($price,2,',','.').' TL</p>';}echo '</main></body></html>';}
    public function pdf(): void{$account=$this->account();$pdf=PdfPriceList::build((string)$account['company_name'].' Fiyat Listesi',$this->rows(),(float)$account['discount_percent']);header('Content-Type: application/pdf');header('Content-Disposition: attachment; filename="fiyat-listesi.pdf"');header('Content-Length: '.strlen($pdf));echo $pdf;}
    private function account(): array{$id=(int)($_SESSION['b2b_id']??0);$row=$id?App::db()->fetch('SELECT * FROM b2b_accounts WHERE id=? AND is_active=1',[$id]):null;if(!$row){header('Location: /bayi/giris');exit;}return $row;}
    private function rows(): array{return App::db()->fetchAll('SELECT v.sku,v.name variant_name,v.price,p.name product_name FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.is_active=1 AND p.status=\'published\' ORDER BY p.name,v.name');}
}
