<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\AdminView;use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Locale;use Arcates\Core\Security;use Arcates\Core\Text;
final class BlogAdminController
{
 public function index(): void{AdminView::header('Blog');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<p><a href="/'.$a.'/blog/yeni">Yeni yazı</a></p>';foreach(App::db()->fetchAll('SELECT id,locale,title,status,category FROM blog_posts ORDER BY updated_at DESC') as $p)echo '<article class="card"><strong>'.Security::escape($p['locale'].' · '.$p['title']).'</strong><p>'.Security::escape($p['status'].' · '.$p['category']).'</p><a href="/'.$a.'/blog/duzenle?id='.(int)$p['id'].'">Düzenle</a></article>';AdminView::footer();}
 public function createForm(): void{$this->form(null);}public function editForm(): void{$p=App::db()->fetch('SELECT * FROM blog_posts WHERE id=?',[(int)($_GET['id']??0)]);if(!$p){http_response_code(404);return;}$this->form($p);}
 public function save(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$id=(int)($_POST['id']??0);$locale=(string)($_POST['locale']??'tr');if(!Locale::valid($locale))throw new \RuntimeException('Geçersiz dil.');$title=trim((string)($_POST['title']??''));if($title==='')throw new \RuntimeException('Başlık gerekli.');$slug=Text::slug((string)($_POST['slug']??$title));$status=in_array($_POST['status']??'',['draft','published'],true)?(string)$_POST['status']:'draft';$params=[$locale,$title,$slug,mb_substr(trim((string)($_POST['excerpt']??'')),0,500),(string)($_POST['body']??''),mb_substr(trim((string)($_POST['category']??'')),0,120),mb_substr(trim((string)($_POST['tags']??'')),0,500),$status,mb_substr(trim((string)($_POST['meta_title']??'')),0,190),mb_substr(trim((string)($_POST['meta_description']??'')),0,320)];if($id){App::db()->execute('UPDATE blog_posts SET locale=?,title=?,slug=?,excerpt=?,body=?,category=?,tags=?,status=?,meta_title=?,meta_description=?,published_at=CASE WHEN ?=? AND published_at IS NULL THEN NOW() ELSE published_at END,updated_at=NOW() WHERE id=?',array_merge($params,[$status,'published',$id]));}else{App::db()->execute('INSERT INTO blog_posts(locale,title,slug,excerpt,body,category,tags,status,meta_title,meta_description,published_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,CASE WHEN ?=? THEN NOW() ELSE NULL END,NOW(),NOW())',array_merge($params,[$status,'published']));}$this->back();}
 public function delete(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);App::db()->execute('DELETE FROM blog_posts WHERE id=?',[(int)($_POST['id']??0)]);$this->back();}
 private function form(?array $p): void{AdminView::header($p?'Blog yazısı düzenle':'Yeni blog yazısı');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<form class="card" method="post" action="/'.$a.'/blog/kaydet">'.Csrf::field().'<input type="hidden" name="id" value="'.(int)($p['id']??0).'"><label>Dil<select name="locale">';foreach(Locale::supported() as $l)echo '<option'.(($p['locale']??'tr')===$l?' selected':'').'>'.Security::escape($l).'</option>';echo '</select></label><label>Başlık<input name="title" required value="'.Security::escape($p['title']??'').'"></label><label>Slug<input name="slug" value="'.Security::escape($p['slug']??'').'"></label><label>Özet<textarea name="excerpt">'.Security::escape($p['excerpt']??'').'</textarea></label><label>İçerik<textarea name="body" rows="12">'.Security::escape($p['body']??'').'</textarea></label><div class="grid two"><label>Kategori<input name="category" value="'.Security::escape($p['category']??'').'"></label><label>Etiketler<input name="tags" value="'.Security::escape($p['tags']??'').'"></label></div><label>Durum<select name="status"><option value="draft">Taslak</option><option value="published"'.(($p['status']??'')==='published'?' selected':'').'>Yayında</option></select></label><label>Meta title<input name="meta_title" value="'.Security::escape($p['meta_title']??'').'"></label><label>Meta description<textarea name="meta_description">'.Security::escape($p['meta_description']??'').'</textarea></label><button>Kaydet</button></form>';if($p)echo '<form class="card" method="post" action="/'.$a.'/blog/sil">'.Csrf::field().'<input type="hidden" name="id" value="'.(int)$p['id'].'"><button data-confirm="Yazı silinsin mi?">Sil</button></form>';AdminView::footer();}
 private function back(): void{header('Location: /'.App::config('app.admin_path','yonetim').'/blog');}
}
