<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\App;use Arcates\Core\Locale;use Arcates\Core\Security;use Arcates\Core\WhatsApp;
final class BlogController
{
 public function index(string $locale): void{if(!Locale::valid($locale)){http_response_code(404);return;}$posts=App::db()->fetchAll('SELECT title,slug,excerpt,category,published_at FROM blog_posts WHERE locale=? AND status=? ORDER BY published_at DESC,id DESC',[$locale,'published']);echo '<!doctype html><html lang="'.Security::escape($locale).'" dir="'.(Locale::rtl($locale)?'rtl':'ltr').'"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Blog</title><link rel="stylesheet" href="/assets/css/theme.css"><body><main class="container"><h1>Blog</h1>';foreach($posts as $p){echo '<article><h2><a href="/blog/'.Security::escape($locale).'/'.Security::escape($p['slug']).'">'.Security::escape($p['title']).'</a></h2><p>'.Security::escape($p['excerpt']).'</p><small>'.Security::escape($p['category']).'</small></article>';}echo '</main>'.WhatsApp::button().'</body></html>';}
 public function show(string $locale,string $slug): void{if(!Locale::valid($locale)){http_response_code(404);return;}$p=App::db()->fetch('SELECT * FROM blog_posts WHERE locale=? AND slug=? AND status=? LIMIT 1',[$locale,$slug,'published']);if(!$p){http_response_code(404);return;}$title=Security::escape($p['meta_title']?:$p['title']);$desc=Security::escape($p['meta_description']?:$p['excerpt']);echo '<!doctype html><html lang="'.Security::escape($locale).'" dir="'.(Locale::rtl($locale)?'rtl':'ltr').'"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.$title.'</title><meta name="description" content="'.$desc.'"><link rel="stylesheet" href="/assets/css/theme.css"><body><main class="container"><article><h1>'.Security::escape($p['title']).'</h1><p>'.nl2br(Security::escape($p['body'])).'</p><p>Etiketler: '.Security::escape($p['tags']).'</p></article></main>'.WhatsApp::button('Merhaba, '.(string)$p['title'].' yazısı hakkında bilgi almak istiyorum.').'</body></html>';}
}
