<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\AdminView;use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Security;use Arcates\Shipping\CarrierFactory;
final class CarrierAdminController
{
 public function index(): void
 {
  AdminView::header('Kargo Entegrasyonları');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<p>MNG/DHL eCommerce, Aras ve Yurtiçi hesap bilgileri yalnız <code>config.php</code> içinde tutulur.</p><h2>Gönderime hazır siparişler</h2>';
  foreach(App::db()->fetchAll("SELECT o.id,o.public_code,o.customer_name,o.city,o.grand_total,o.status,o.payment_status FROM orders o WHERE o.status IN ('confirmed','preparing') ORDER BY o.id DESC LIMIT 100") as $o){echo '<article class="card"><strong>'.Security::escape($o['public_code'].' · '.$o['customer_name']).'</strong><p>'.Security::escape($o['city'].' · '.$o['status'].' · '.$o['payment_status']).'</p><form method="post" action="/'.$a.'/kargo-entegrasyon/olustur">'.Csrf::field().'<input type="hidden" name="order_id" value="'.(int)$o['id'].'"><select name="provider"><option value="mng">MNG / DHL eCommerce</option><option value="aras">Aras</option><option value="yurtici">Yurtiçi</option></select><input name="district" required maxlength="120" placeholder="Alıcı ilçesi"><label>KG<input type="number" name="kg" min="0.01" max="9999" step="0.01" value="1"></label><label>Desi<input type="number" name="desi" min="0.01" max="9999" step="0.01" value="1"></label><label>Koli<input type="number" name="count" min="1" max="999" step="1" value="1"></label><button>Taşıyıcıya gönder</button></form></article>';}
  echo '<h2>Kargo kayıtları</h2>';foreach(App::db()->fetchAll('SELECT cs.*,o.public_code,o.customer_name FROM carrier_shipments cs JOIN orders o ON o.id=cs.order_id ORDER BY cs.updated_at DESC,cs.id DESC LIMIT 200') as $s){echo '<article class="card"><strong>'.Security::escape(strtoupper($s['provider']).' · '.$s['reference_code']).'</strong><p>'.Security::escape($s['public_code'].' · '.$s['customer_name']).'</p><p>Takip: '.Security::escape((string)$s['tracking_number']).' · Durum: '.Security::escape((string)$s['provider_status']).'</p>'.($s['last_message']?'<p>'.Security::escape($s['last_message']).'</p>':'').'<div class="grid two"><form method="post" action="/'.$a.'/kargo-entegrasyon/takip">'.Csrf::field().'<input type="hidden" name="id" value="'.(int)$s['id'].'"><button>Takibi güncelle</button></form><form method="post" action="/'.$a.'/kargo-entegrasyon/etiket">'.Csrf::field().'<input type="hidden" name="id" value="'.(int)$s['id'].'"><button>Etiket oluştur/indir</button></form></div></article>';}AdminView::footer();
 }
 public function create(): void
 {
  AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$orderId=(int)($_POST['order_id']??0);$provider=strtolower(trim((string)($_POST['provider']??'')));if(!in_array($provider,CarrierFactory::supported(),true))throw new \RuntimeException('Geçersiz kargo sağlayıcısı.');$district=mb_substr(trim((string)($_POST['district']??'')),0,120);$kg=(float)($_POST['kg']??0);$desi=(float)($_POST['desi']??0);$count=(int)($_POST['count']??0);if($district===''||$kg<=0||$kg>9999||$desi<=0||$desi>9999||$count<1||$count>999)throw new \RuntimeException('Kargo paket bilgileri geçersiz.');$order=App::db()->fetch("SELECT * FROM orders WHERE id=? AND status IN ('confirmed','preparing')",[$orderId]);if(!$order)throw new \RuntimeException('Gönderime uygun sipariş bulunamadı.');if(App::db()->fetch('SELECT id FROM carrier_shipments WHERE order_id=? AND provider=?',[$orderId,$provider]))throw new \RuntimeException('Bu sipariş sağlayıcıya daha önce gönderilmiş.');$result=CarrierFactory::make($provider)->create($order,['district'=>$district,'kg'=>$kg,'desi'=>$desi,'count'=>$count]);App::db()->transaction(function($db)use($orderId,$provider,$district,$kg,$desi,$count,$result): void{$db->execute('INSERT INTO carrier_shipments(order_id,provider,reference_code,tracking_number,provider_status,recipient_district,package_count,weight_kg,desi,last_message,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[$orderId,$provider,(string)$result['reference'],(string)($result['tracking']??''),(string)($result['status']??''),$district,$count,$kg,$desi,mb_substr((string)($result['message']??''),0,500)?:null]);$db->execute("UPDATE orders SET status='preparing',updated_at=NOW() WHERE id=? AND status='confirmed'",[$orderId]);});$this->back();
 }
 public function track(): void
 {
  AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$row=$this->row((int)($_POST['id']??0));$result=CarrierFactory::make((string)$row['provider'])->track((string)$row['reference_code']);App::db()->execute('UPDATE carrier_shipments SET provider_status=?,last_message=?,updated_at=NOW() WHERE id=?',[mb_substr((string)($result['status']??''),0,120),mb_substr((string)($result['message']??''),0,500)?:null,(int)$row['id']]);$this->back();
 }
 public function label(): void
 {
  AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$row=$this->row((int)($_POST['id']??0));$label=CarrierFactory::make((string)$row['provider'])->label((string)$row['reference_code']);$content=(string)($label['content']??'');if($content==='')throw new \RuntimeException('Etiket içeriği boş.');header('Content-Type: '.(string)($label['content_type']??'application/octet-stream'));header('Content-Disposition: attachment; filename="'.preg_replace('/[^A-Za-z0-9._-]/','_',(string)($label['filename']??'label.bin')).'"');header('Content-Length: '.strlen($content));echo $content;
 }
 private function row(int $id): array{$row=App::db()->fetch('SELECT * FROM carrier_shipments WHERE id=?',[$id]);if(!$row)throw new \RuntimeException('Kargo kaydı bulunamadı.');return $row;}
 private function back(): void{header('Location: /'.App::config('app.admin_path','yonetim').'/kargo-entegrasyon');}
}
