<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\AdminView;use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Security;use Arcates\Core\Text;use Arcates\Core\Upload;
final class GalleryAdminController
{
 public function index(): void{AdminView::header('Portföy');$cats=App::db()->fetchAll('SELECT * FROM gallery_categories ORDER BY name');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<form class="card" method="post" action="/'.$a.'/portfoy/kategori">'.Csrf::field().'<label>Kategori adı<input name="name" required maxlength="190"></label><button>Kategori ekle</button></form><form class="card" method="post" enctype="multipart/form-data" action="/'.$a.'/portfoy/ekle">'.Csrf::field().'<label>Kategori<select name="category_id">';foreach($cats as $c)echo '<option value="'.(int)$c['id'].'">'.Security::escape($c['name']).'</option>';echo '</select></label><label>Başlık<input name="title" required maxlength="190"></label><label>Alt metin<input name="alt" required maxlength="255"></label><label>Sıra<input type="number" name="sort_order" value="0"></label><label>Görsel<input type="file" name="image" required accept="image/jpeg,image/png,image/webp"></label><button>Görsel ekle</button></form>';foreach(App::db()->fetchAll('SELECT gi.id,gi.title,gi.image_path,gc.name category_name FROM gallery_items gi JOIN gallery_categories gc ON gc.id=gi.category_id ORDER BY gc.name,gi.sort_order,gi.id') as $i){echo '<article class="card"><strong>'.Security::escape($i['category_name'].' · '.$i['title']).'</strong><br><img loading="lazy" width="180" src="'.Security::escape($i['image_path']).'" alt=""><form method="post" action="/'.$a.'/portfoy/sil">'.Csrf::field().'<input type="hidden" name="id" value="'.(int)$i['id'].'"><button data-confirm="Görsel silinsin mi?">Sil</button></form></article>';}AdminView::footer();}
 public function addCategory(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$name=trim((string)($_POST['name']??''));if($name==='')throw new \RuntimeException('Kategori adı gerekli.');App::db()->execute('INSERT INTO gallery_categories(name,slug,created_at) VALUES(?,?,NOW())',[$name,Text::slug($name)]);$this->back();}
 public function addItem(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$r=Upload::image($_FILES['image']??[]);App::db()->execute('INSERT INTO gallery_items(category_id,title,image_path,alt_text,sort_order,created_at) VALUES(?,?,?,?,?,NOW())',[(int)($_POST['category_id']??0),trim((string)($_POST['title']??'')),$r['path'],trim((string)($_POST['alt']??'')),(int)($_POST['sort_order']??0)]);$this->back();}
 public function delete(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);App::db()->execute('DELETE FROM gallery_items WHERE id=?',[(int)($_POST['id']??0)]);$this->back();}
 private function back(): void{header('Location: /'.App::config('app.admin_path','yonetim').'/portfoy');}
}
