<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\AdminView;use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Locale;use Arcates\Core\Security;use Arcates\Core\Text;
final class PageAdminController
{
 public function index(): void{AdminView::header('Sayfalar');$rows=App::db()->fetchAll('SELECT id, locale, title, slug, status, updated_at FROM pages ORDER BY updated_at DESC');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<p><a href="/'.$a.'/sayfalar/yeni">Yeni sayfa</a></p><div class="card"><table class="table"><thead><tr><th>Dil</th><th>Başlık</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>';foreach($rows as $r){echo '<tr><td>'.Security::escape($r['locale']).'</td><td>'.Security::escape($r['title']).'</td><td>'.Security::escape($r['status']).'</td><td><a href="/'.$a.'/sayfalar/duzenle?id='.(int)$r['id'].'">Düzenle</a></td></tr>';}echo '</tbody></table></div>';AdminView::footer();}
 public function createForm(): void{$this->form(null);} public function editForm(): void{$id=(int)($_GET['id']??0);$p=App::db()->fetch('SELECT * FROM pages WHERE id = ?',[$id]);if(!$p){http_response_code(404);return;}$this->form($p);}
 public function save(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$id=(int)($_POST['id']??0);$locale=(string)($_POST['locale']??'tr');if(!Locale::valid($locale))throw new \RuntimeException('Geçersiz dil.');$title=trim((string)($_POST['title']??''));if($title==='')throw new \RuntimeException('Başlık gerekli.');$slug=Text::slug((string)($_POST['slug']??$title));$status=in_array($_POST['status']??'', ['draft','published'],true)?(string)$_POST['status']:'draft';$body=(string)($_POST['body']??'');$mt=mb_substr(trim((string)($_POST['meta_title']??'')),0,190);$md=mb_substr(trim((string)($_POST['meta_description']??'')),0,320);$og=trim((string)($_POST['og_image']??''));if($id>0){App::db()->execute('UPDATE pages SET locale=?, title=?, slug=?, body=?, status=?, meta_title=?, meta_description=?, og_image=?, updated_at=NOW() WHERE id=?',[$locale,$title,$slug,$body,$status,$mt,$md,$og,$id]);}else{App::db()->execute('INSERT INTO pages (locale,title,slug,body,status,meta_title,meta_description,og_image,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,NOW(),NOW())',[$locale,$title,$slug,$body,$status,$mt,$md,$og]);}header('Location: /'.App::config('app.admin_path','yonetim').'/sayfalar');}
 public function delete(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);App::db()->execute('DELETE FROM pages WHERE id = ?',[(int)($_POST['id']??0)]);header('Location: /'.App::config('app.admin_path','yonetim').'/sayfalar');}
 private function form(?array $p): void{AdminView::header($p?'Sayfa düzenle':'Yeni sayfa');$id=(int)($p['id']??0);echo '<form method="post" action="/'.Security::escape((string)App::config('app.admin_path','yonetim')).'/sayfalar/kaydet" class="card">'.Csrf::field().'<input type="hidden" name="id" value="'.$id.'"><label>Dil<select name="locale">';foreach(Locale::supported() as $l){$sel=(($p['locale']??'tr')===$l)?' selected':'';echo '<option'.$sel.'>'.Security::escape($l).'</option>';}echo '</select></label><label>Başlık<input name="title" required value="'.Security::escape($p['title']??'').'"></label><label>Slug<input name="slug" value="'.Security::escape($p['slug']??'').'"></label><label>İçerik<textarea name="body" rows="12">'.Security::escape($p['body']??'').'</textarea></label><label>Durum<select name="status"><option value="draft">Taslak</option><option value="published"'.(($p['status']??'')==='published'?' selected':'').'>Yayında</option></select></label><div class="grid two"><label>Meta title<input name="meta_title" maxlength="190" value="'.Security::escape($p['meta_title']??'').'"></label><label>OG görsel URL<input name="og_image" value="'.Security::escape($p['og_image']??'').'"></label></div><label>Meta description<textarea name="meta_description" maxlength="320">'.Security::escape($p['meta_description']??'').'</textarea></label><button>Kaydet</button></form>';if($p){echo '<form method="post" action="/'.Security::escape((string)App::config('app.admin_path','yonetim')).'/sayfalar/sil" class="card">'.Csrf::field().'<input type="hidden" name="id" value="'.$id.'"><button data-confirm="Sayfa silinsin mi?">Sil</button></form>';}AdminView::footer();}
}
