<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\App;use Arcates\Payments\GatewayFactory;use Arcates\Services\Mailer;use Arcates\Services\OrderService;
final class PaymentController
{
    public function start(): void
    {
        $code=(string)($_GET['order']??'');$order=App::db()->fetch('SELECT * FROM orders WHERE public_code=?',[$code]);if(!$order){http_response_code(404);return;}if($order['status']==='cancelled')throw new \RuntimeException('İptal edilmiş sipariş ödenemez.');if($order['payment_status']==='paid'){header('Location: /odeme/sonuc?order='.rawurlencode($code));return;}$items=App::db()->fetchAll('SELECT * FROM order_items WHERE order_id=?',[(int)$order['id']]);
        try{App::db()->execute('UPDATE orders SET payment_provider=? WHERE id=?',['iyzico',(int)$order['id']]);$gateway=GatewayFactory::make();$callback=rtrim((string)App::config('app.url',''),'/').'/odeme/sonuc';$result=$gateway->initialize($order,$items,$callback);App::db()->execute('INSERT INTO payment_attempts(order_id,provider,provider_token,status,error_code,created_at) VALUES(?,?,?,?,?,NOW())',[(int)$order['id'],'iyzico',$result['token']?:null,$result['status']==='success'?'initialized':'failed',$result['error_code']?:null]);if($result['status']!=='success'||$result['page_url']==='')throw new \RuntimeException('Ödeme başlatılamadı: '.($result['error_message']?:$result['error_code']));header('Location: '.$result['page_url']);}catch(\Throwable $e){OrderService::cancel((int)$order['id']);throw $e;}
    }
    public function callback(): void
    {
        $token=trim((string)($_POST['token']??$_GET['token']??''));if($token===''){if(isset($_GET['order'])){$o=App::db()->fetch('SELECT public_code,payment_status,status FROM orders WHERE public_code=?',[(string)$_GET['order']]);if($o){$ok=$o['payment_status']==='paid';echo '<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ödeme sonucu</title><body><main><h1>'.($ok?'Ödeme başarılı':'Sipariş durumu').'</h1><p>Sipariş kodu: '.htmlspecialchars((string)$o['public_code'],ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</p><p>Durum: '.htmlspecialchars((string)$o['status'],ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</p></main></body></html>';return;}}http_response_code(400);echo 'Eksik ödeme tokenı.';return;}
        $attempt=App::db()->fetch('SELECT pa.id,pa.order_id,o.public_code,o.payment_status FROM payment_attempts pa JOIN orders o ON o.id=pa.order_id WHERE pa.provider_token=? ORDER BY pa.id DESC LIMIT 1',[$token]);if(!$attempt){http_response_code(404);return;}$result=GatewayFactory::make()->retrieve($token,(string)$attempt['public_code']);$paid=$attempt['payment_status']==='paid'||($result['status']==='success'&&strtoupper($result['payment_status'])==='SUCCESS');App::db()->transaction(function($db)use($attempt,$result,$paid): void{$db->execute('UPDATE payment_attempts SET status=?,error_code=? WHERE id=?',[$paid?'success':'failed',$result['error_code']?:null,(int)$attempt['id']]);if($paid)$db->execute('UPDATE orders SET payment_status=\'paid\',payment_reference=?,status=\'confirmed\',updated_at=NOW() WHERE id=?',[$result['payment_id']?:null,(int)$attempt['order_id']]);else$db->execute('UPDATE orders SET payment_status=\'failed\',updated_at=NOW() WHERE id=?',[(int)$attempt['order_id']]);});if(!$paid)OrderService::cancel((int)$attempt['order_id']);$order=App::db()->fetch('SELECT * FROM orders WHERE id=?',[(int)$attempt['order_id']]);if($order)Mailer::orderStatus($order);echo '<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ödeme sonucu</title><body><main><h1>'.($paid?'Ödeme başarılı':'Ödeme başarısız').'</h1><p>Sipariş kodu: '.htmlspecialchars((string)$attempt['public_code'],ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</p></main></body></html>';
    }
}
