<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\AdminView;use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Locale;use Arcates\Core\Security;use Arcates\Core\Text;
final class ProductAdminController
{
    public function index(): void{AdminView::header('Ürünler');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<form class="card" method="post" action="/'.$a.'/urunler/ekle">'.Csrf::field().'<label>Dil<select name="locale">';foreach(Locale::supported() as $l)echo '<option>'.Security::escape($l).'</option>';echo '</select></label><label>Ürün adı<input name="name" required></label><label>Slug<input name="slug"></label><label>Açıklama<textarea name="description"></textarea></label><label>Görsel yolu<input name="image_path"></label><label>Başlangıç fiyatı<input type="number" step="0.01" min="0" name="base_price" value="0"></label><label>Durum<select name="status"><option value="draft">Taslak</option><option value="published">Yayında</option></select></label><button>Ürün ekle</button></form>';foreach(App::db()->fetchAll('SELECT * FROM products ORDER BY updated_at DESC') as $p){echo '<section class="card"><h2>'.Security::escape($p['name']).'</h2><p>'.Security::escape($p['locale'].' · '.$p['status']).'</p><form method="post" action="/'.$a.'/urunler/varyant">'.Csrf::field().'<input type="hidden" name="product_id" value="'.(int)$p['id'].'"><label>SKU<input name="sku" required maxlength="120"></label><label>Varyant<input name="name" required maxlength="190"></label><label>Fiyat<input type="number" step="0.01" min="0" name="price" required></label><label>Stok<input type="number" min="0" name="stock" required></label><button>Varyant ekle</button></form>';foreach(App::db()->fetchAll('SELECT sku,name,price,stock FROM product_variants WHERE product_id=? ORDER BY id',[(int)$p['id']]) as $v)echo '<p>'.Security::escape($v['sku'].' · '.$v['name']).' · '.number_format((float)$v['price'],2,',','.').' TL · stok '.(int)$v['stock'].'</p>';echo '</section>';}AdminView::footer();}
    public function add(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$locale=(string)($_POST['locale']??'tr');if(!Locale::valid($locale))throw new \RuntimeException('Geçersiz dil.');$name=trim((string)($_POST['name']??''));if($name==='')throw new \RuntimeException('Ürün adı gerekli.');$slug=Text::slug((string)($_POST['slug']??$name));$status=in_array($_POST['status']??'',['draft','published'],true)?(string)$_POST['status']:'draft';App::db()->execute('INSERT INTO products(locale,name,slug,description,image_path,status,base_price,created_at,updated_at) VALUES(?,?,?,?,?,?,?,NOW(),NOW())',[$locale,mb_substr($name,0,190),$slug,(string)($_POST['description']??''),mb_substr(trim((string)($_POST['image_path']??'')),0,255)?:null,$status,max(0,(float)($_POST['base_price']??0))]);$this->back();}
    public function addVariant(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$sku=strtoupper(trim((string)($_POST['sku']??'')));$name=trim((string)($_POST['name']??''));if($sku===''||$name==='')throw new \RuntimeException('SKU ve varyant adı gerekli.');App::db()->execute('INSERT INTO product_variants(product_id,sku,name,price,stock,is_active,created_at,updated_at) VALUES(?,?,?,?,?,1,NOW(),NOW())',[(int)($_POST['product_id']??0),mb_substr($sku,0,120),mb_substr($name,0,190),max(0,(float)($_POST['price']??0)),max(0,(int)($_POST['stock']??0))]);$this->back();}
    private function back(): void{header('Location: /'.App::config('app.admin_path','yonetim').'/urunler');}
}
