<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\AdminView;use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Locale;use Arcates\Core\Security;use Arcates\Core\Text;
final class QrMenuAdminController
{
 public function index(): void
 {
  AdminView::header('QR Menü');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<form class="card" method="post" action="/'.$a.'/qr-menu/menu">'.Csrf::field().'<h2>Menü oluştur</h2><input name="name" required maxlength="190" placeholder="Menü adı"><input name="slug" maxlength="190" placeholder="slug"><button>Oluştur</button></form>';foreach(App::db()->fetchAll('SELECT * FROM qr_menus ORDER BY id DESC') as $m){echo '<section class="card"><h2>'.Security::escape($m['name']).'</h2><p><a target="_blank" href="/menu/'.Security::escape($m['slug']).'/tr">Menüyü aç</a> · <a target="_blank" href="/menu/'.Security::escape($m['slug']).'/qr.svg?locale=tr">QR</a></p><form method="post" action="/'.$a.'/qr-menu/kategori">'.Csrf::field().'<input type="hidden" name="menu_id" value="'.(int)$m['id'].'"><select name="locale">';foreach(Locale::supported() as $l)echo '<option>'.Security::escape($l).'</option>';echo '</select><input name="name" required maxlength="190" placeholder="Kategori"><button>Kategori ekle</button></form>';foreach(App::db()->fetchAll('SELECT * FROM qr_menu_categories WHERE menu_id=? ORDER BY locale,sort_order,id',[(int)$m['id']]) as $c){echo '<div class="card"><strong>'.Security::escape($c['locale'].' · '.$c['name']).'</strong><form method="post" action="/'.$a.'/qr-menu/urun">'.Csrf::field().'<input type="hidden" name="category_id" value="'.(int)$c['id'].'"><input name="name" required maxlength="190" placeholder="Ürün adı"><input name="description" maxlength="500" placeholder="Açıklama"><input type="number" step="0.01" min="0" name="price" value="0"><input name="image_path" maxlength="255" placeholder="Görsel yolu"><button>Ürün ekle</button></form>';foreach(App::db()->fetchAll('SELECT name,price,currency FROM qr_menu_items WHERE category_id=? ORDER BY sort_order,id',[(int)$c['id']]) as $i)echo '<p>'.Security::escape($i['name']).' · '.number_format((float)$i['price'],2,',','.').' '.Security::escape($i['currency']).'</p>';echo '</div>';}echo '</section>';}AdminView::footer();
 }
 public function addMenu(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$name=trim((string)($_POST['name']??''));if($name==='')throw new \RuntimeException('Menü adı gerekli.');App::db()->execute('INSERT INTO qr_menus(name,slug,is_active,created_at) VALUES(?,?,1,NOW())',[mb_substr($name,0,190),Text::slug((string)($_POST['slug']??$name))]);$this->back();}
 public function addCategory(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$locale=(string)($_POST['locale']??'tr');$name=trim((string)($_POST['name']??''));if(!Locale::valid($locale)||$name==='')throw new \RuntimeException('Kategori bilgisi geçersiz.');App::db()->execute('INSERT INTO qr_menu_categories(menu_id,locale,name,sort_order,created_at) VALUES(?,?,?,0,NOW())',[(int)($_POST['menu_id']??0),$locale,mb_substr($name,0,190)]);$this->back();}
 public function addItem(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$name=trim((string)($_POST['name']??''));if($name==='')throw new \RuntimeException('Ürün adı gerekli.');App::db()->execute('INSERT INTO qr_menu_items(category_id,name,description,price,currency,image_path,is_active,sort_order,created_at) VALUES(?,?,?,?,?,?,1,0,NOW())',[(int)($_POST['category_id']??0),mb_substr($name,0,190),mb_substr(trim((string)($_POST['description']??'')),0,500)?:null,max(0,(float)($_POST['price']??0)),'TRY',mb_substr(trim((string)($_POST['image_path']??'')),0,255)?:null]);$this->back();}
 private function back(): void{header('Location: /'.App::config('app.admin_path','yonetim').'/qr-menu');}
}
