<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\App;use Arcates\Core\Locale;use Arcates\Core\Security;
final class RealEstateController
{
 public function index(string $locale='tr'): void
 {
  if(!Locale::valid($locale))$locale='tr';$where=['locale=?','status=\'published\''];$params=[$locale];$map=['listing_type'=>['sale','rent'],'property_type'=>null,'city'=>null,'district'=>null,'rooms'=>null];foreach($map as $key=>$allowed){$v=trim((string)($_GET[$key]??''));if($v==='')continue;if(is_array($allowed)&&!in_array($v,$allowed,true))continue;$where[]=$key.'=?';$params[]=$v;}foreach(['min_price'=>['price','>='],'max_price'=>['price','<='],'min_m2'=>['area_m2','>='],'max_m2'=>['area_m2','<=']] as $key=>$rule){$v=$_GET[$key]??'';if($v!==''&&is_numeric($v)){$where[]=$rule[0].$rule[1].'?';$params[]=max(0,(float)$v);}}$rows=App::db()->fetchAll('SELECT * FROM real_estate_listings WHERE '.implode(' AND ',$where).' ORDER BY updated_at DESC LIMIT 100',$params);echo '<!doctype html><html lang="'.Security::escape($locale).'"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Emlak ilanları</title><link rel="stylesheet" href="/assets/css/theme.css"><body><main class="container"><h1>Emlak ilanları</h1><form class="card" method="get"><input name="city" placeholder="Şehir" value="'.Security::escape((string)($_GET['city']??'')).'"><input name="district" placeholder="İlçe" value="'.Security::escape((string)($_GET['district']??'')).'"><select name="listing_type"><option value="">Satılık/Kiralık</option><option value="sale">Satılık</option><option value="rent">Kiralık</option></select><input name="rooms" placeholder="Oda"><input type="number" name="min_m2" min="0" placeholder="Min m²"><input type="number" name="max_price" min="0" placeholder="Max fiyat"><button>Filtrele</button></form><div class="grid">';foreach($rows as $r){echo '<article class="card">'.($r['image_path']?'<img loading="lazy" src="'.Security::escape($r['image_path']).'" alt="'.Security::escape($r['title']).'">':'').'<h2><a href="/emlak/'.Security::escape($locale).'/'.Security::escape($r['slug']).'">'.Security::escape($r['title']).'</a></h2><p>'.Security::escape($r['city'].' / '.$r['district']).' · '.Security::escape((string)$r['rooms']).' · '.Security::escape((string)$r['area_m2']).' m²</p><strong>'.number_format((float)$r['price'],2,',','.').' '.Security::escape($r['currency']).'</strong></article>';}echo '</div></main></body></html>';
 }
 public function show(string $locale,string $slug): void
 {
  if(!Locale::valid($locale)){http_response_code(404);return;}$r=App::db()->fetch('SELECT * FROM real_estate_listings WHERE locale=? AND slug=? AND status=\'published\'',[$locale,$slug]);if(!$r){http_response_code(404);return;}$map='';if($r['latitude']!==null&&$r['longitude']!==null){$lat=rawurlencode((string)$r['latitude']);$lon=rawurlencode((string)$r['longitude']);$map='<p><a rel="noopener" target="_blank" href="https://www.openstreetmap.org/?mlat='.$lat.'&mlon='.$lon.'#map=16/'.$lat.'/'.$lon.'">Haritada aç</a></p>';}echo '<!doctype html><html lang="'.Security::escape($locale).'"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.Security::escape($r['title']).'</title><link rel="stylesheet" href="/assets/css/theme.css"><body><main class="container"><h1>'.Security::escape($r['title']).'</h1>'.($r['image_path']?'<img src="'.Security::escape($r['image_path']).'" alt="'.Security::escape($r['title']).'">':'').'<p>'.Security::escape($r['city'].' / '.$r['district'].' / '.($r['neighborhood']??'')).'</p><p>'.Security::escape((string)$r['area_m2']).' m² · '.Security::escape((string)$r['rooms']).' · '.Security::escape((string)$r['floor']).'</p><strong>'.number_format((float)$r['price'],2,',','.').' '.Security::escape($r['currency']).'</strong><p>'.nl2br(Security::escape($r['description'])).'</p>'.$map.'</main></body></html>';
 }
}
