<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\AdminView;use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Locale;use Arcates\Core\Security;use Arcates\Core\Text;
final class RealEstateAdminController
{
 public function index(): void{AdminView::header('Emlak ilanları');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<form class="card" method="post" action="/'.$a.'/emlak/ekle">'.Csrf::field().'<label>Dil<select name="locale">';foreach(Locale::supported() as $l)echo '<option>'.Security::escape($l).'</option>';echo '</select></label><label>Başlık<input name="title" required maxlength="190"></label><label>Slug<input name="slug"></label><div class="grid two"><label>İlan<select name="listing_type"><option value="sale">Satılık</option><option value="rent">Kiralık</option></select></label><label>Tip<input name="property_type" required maxlength="80" placeholder="Daire, arsa..."></label><label>Şehir<input name="city" required maxlength="120"></label><label>İlçe<input name="district" required maxlength="120"></label><label>Mahalle<input name="neighborhood" maxlength="120"></label><label>Fiyat<input type="number" step="0.01" min="0" name="price" required></label><label>m²<input type="number" step="0.01" min="0" name="area_m2" required></label><label>Oda<input name="rooms" maxlength="30"></label><label>Kat<input name="floor" maxlength="30"></label><label>Enlem<input type="number" step="0.0000001" name="latitude"></label><label>Boylam<input type="number" step="0.0000001" name="longitude"></label></div><label>Görsel yolu<input name="image_path" maxlength="255"></label><label>Açıklama<textarea name="description" rows="8"></textarea></label><label>Durum<select name="status"><option value="draft">Taslak</option><option value="published">Yayında</option></select></label><button>İlan ekle</button></form>';foreach(App::db()->fetchAll('SELECT id,locale,title,status,price,currency FROM real_estate_listings ORDER BY updated_at DESC') as $r)echo '<article class="card"><strong>'.Security::escape($r['locale'].' · '.$r['title']).'</strong><p>'.Security::escape($r['status']).' · '.number_format((float)$r['price'],2,',','.').' '.Security::escape($r['currency']).'</p><form method="post" action="/'.$a.'/emlak/sil">'.Csrf::field().'<input type="hidden" name="id" value="'.(int)$r['id'].'"><button data-confirm="İlan silinsin mi?">Sil</button></form></article>';AdminView::footer();}
 public function add(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$locale=(string)($_POST['locale']??'tr');if(!Locale::valid($locale))throw new \RuntimeException('Geçersiz dil.');$title=trim((string)($_POST['title']??''));$type=trim((string)($_POST['property_type']??''));$city=trim((string)($_POST['city']??''));$district=trim((string)($_POST['district']??''));if($title===''||$type===''||$city===''||$district==='')throw new \RuntimeException('Zorunlu alanlar eksik.');$status=in_array($_POST['status']??'',['draft','published'],true)?(string)$_POST['status']:'draft';$listing=in_array($_POST['listing_type']??'',['sale','rent'],true)?(string)$_POST['listing_type']:'sale';$lat=trim((string)($_POST['latitude']??''));$lon=trim((string)($_POST['longitude']??''));if($lat!==''&&(!is_numeric($lat)||(float)$lat < -90||(float)$lat>90))throw new \RuntimeException('Geçersiz enlem.');if($lon!==''&&(!is_numeric($lon)||(float)$lon < -180||(float)$lon>180))throw new \RuntimeException('Geçersiz boylam.');App::db()->execute('INSERT INTO real_estate_listings(locale,title,slug,listing_type,property_type,city,district,neighborhood,price,currency,area_m2,rooms,floor,latitude,longitude,description,image_path,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[$locale,mb_substr($title,0,190),Text::slug((string)($_POST['slug']??$title)),$listing,mb_substr($type,0,80),mb_substr($city,0,120),mb_substr($district,0,120),mb_substr(trim((string)($_POST['neighborhood']??'')),0,120)?:null,max(0,(float)($_POST['price']??0)),'TRY',max(0,(float)($_POST['area_m2']??0)),mb_substr(trim((string)($_POST['rooms']??'')),0,30)?:null,mb_substr(trim((string)($_POST['floor']??'')),0,30)?:null,$lat===''?null:(float)$lat,$lon===''?null:(float)$lon,(string)($_POST['description']??''),mb_substr(trim((string)($_POST['image_path']??'')),0,255)?:null,$status]);$this->back();}
 public function delete(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);App::db()->execute('DELETE FROM real_estate_listings WHERE id=?',[(int)($_POST['id']??0)]);$this->back();}
 private function back(): void{header('Location: /'.App::config('app.admin_path','yonetim').'/emlak');}
}
