<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\AdminView;use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Security;use Arcates\Services\ReservationService;
final class ReservationAdminController
{
 public function index(): void{AdminView::header('Rezervasyon');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<form class="card" method="post" action="/'.$a.'/rezervasyon/birim">'.Csrf::field().'<h2>Birim ekle</h2><label>Ad<input name="name" required></label><label>Tür<select name="unit_type"><option value="room">Oda</option><option value="table">Masa</option><option value="session">Seans</option></select></label><label>Kapasite<input type="number" min="1" name="capacity" value="1"></label><label>Temel fiyat<input type="number" min="0" step="0.01" name="base_price" value="0"></label><button>Ekle</button></form>';$units=App::db()->fetchAll('SELECT * FROM reservation_units ORDER BY name');echo '<form class="card" method="post" action="/'.$a.'/rezervasyon/sezon">'.Csrf::field().'<h2>Sezon fiyatı</h2><label>Birim<select name="unit_id">';foreach($units as $u)echo '<option value="'.(int)$u['id'].'">'.Security::escape($u['name']).'</option>';echo '</select></label><label>Başlangıç<input type="date" name="starts_on" required></label><label>Bitiş<input type="date" name="ends_on" required></label><label>Fiyat<input type="number" min="0" step="0.01" name="price" required></label><button>Kaydet</button></form><h2>Rezervasyonlar</h2>';foreach(App::db()->fetchAll('SELECT r.*,u.name unit_name FROM reservations r JOIN reservation_units u ON u.id=r.unit_id ORDER BY r.created_at DESC LIMIT 300') as $r){echo '<article class="card"><strong>'.Security::escape($r['public_code'].' · '.$r['unit_name']).'</strong><p>'.Security::escape($r['guest_name'].' · '.$r['guest_email']).'</p><p>'.Security::escape($r['starts_at'].' → '.$r['ends_at'].' · '.$r['status'].' · '.$r['total_amount'].' '.$r['currency']).'</p><form class="actions" method="post" action="/'.$a.'/rezervasyon/durum">'.Csrf::field().'<input type="hidden" name="id" value="'.(int)$r['id'].'"><button name="status" value="confirmed">Onayla</button><button name="status" value="cancelled">İptal</button></form></article>';}AdminView::footer();}
 public function addUnit(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$name=trim((string)($_POST['name']??''));if($name==='')throw new \InvalidArgumentException('Birim adı gerekli.');$type=in_array($_POST['unit_type']??'',['room','table','session'],true)?(string)$_POST['unit_type']:'room';App::db()->execute('INSERT INTO reservation_units(name,unit_type,capacity,base_price,currency,is_active,created_at,updated_at) VALUES(?,?,?,?,?,1,NOW(),NOW())',[$name,$type,max(1,(int)($_POST['capacity']??1)),max(0,(float)($_POST['base_price']??0)),'TRY']);$this->back();}
 public function addSeason(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$start=(string)($_POST['starts_on']??'');$end=(string)($_POST['ends_on']??'');if($start===''||$end===''||$end<$start)throw new \InvalidArgumentException('Sezon tarihleri geçersiz.');App::db()->execute('INSERT INTO seasonal_prices(unit_id,starts_on,ends_on,price,created_at) VALUES(?,?,?,?,NOW())',[(int)($_POST['unit_id']??0),$start,$end,max(0,(float)($_POST['price']??0))]);$this->back();}
 public function status(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);(new ReservationService(App::db()))->setStatus((int)($_POST['id']??0),(string)($_POST['status']??''));$this->back();}
 private function back(): void{header('Location: /'.App::config('app.admin_path','yonetim').'/rezervasyon');}
}
