<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\RateLimiter;use Arcates\Core\Security;use Arcates\Services\Mailer;use Arcates\Services\ReservationService;
final class ReservationController
{
 public function form(): void{$units=App::db()->fetchAll('SELECT id,name,unit_type,capacity,base_price,currency FROM reservation_units WHERE is_active=1 ORDER BY name');echo '<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rezervasyon</title><link rel="stylesheet" href="/assets/css/theme.css"><body><main class="container"><h1>Rezervasyon</h1><form method="post">'.Csrf::field().'<label>Birim<select name="unit_id" required>';foreach($units as $u)echo '<option value="'.(int)$u['id'].'">'.Security::escape($u['name'].' · '.$u['base_price'].' '.$u['currency']).'</option>';echo '</select></label><label>Başlangıç<input type="datetime-local" name="starts_at" required></label><label>Bitiş<input type="datetime-local" name="ends_at" required></label><label>Kişi<input type="number" min="1" name="guests" value="1" required></label><label>Ad soyad<input name="guest_name" required maxlength="190"></label><label>E-posta<input type="email" name="guest_email" required maxlength="190"></label><label>Telefon<input name="guest_phone" maxlength="50"></label><label>Not<textarea name="notes" maxlength="3000"></textarea></label><div style="position:absolute;left:-9999px" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><button>Rezervasyon isteği gönder</button></form></main></body></html>';}
 public function submit(): void{Csrf::requireValid($_POST['_csrf']??null);if(trim((string)($_POST['website']??''))!==''){http_response_code(204);return;}$limiter=new RateLimiter(App::db());if(!$limiter->genericAllowed('booking:'.Security::clientIp(),5,600)){http_response_code(429);return;}$name=trim((string)($_POST['guest_name']??''));$email=filter_var($_POST['guest_email']??'',FILTER_VALIDATE_EMAIL);if($name===''||$email===false){http_response_code(422);echo 'Ad ve geçerli e-posta gerekli.';return;}try{$result=(new ReservationService(App::db()))->create(array_merge($_POST,['guest_name'=>$name,'guest_email'=>$email]));Mailer::reservation($result);echo '<p>Rezervasyon isteğiniz alındı. Kod: <strong>'.Security::escape($result['public_code']).'</strong></p>';}catch(\Throwable $e){http_response_code(409);echo '<p>'.Security::escape($e->getMessage()).'</p>';}}
 public function availability(): void{header('Content-Type: application/json; charset=UTF-8');$unit=(int)($_GET['unit_id']??0);$start=(string)($_GET['starts_at']??'');$end=(string)($_GET['ends_at']??'');try{$start=(new \DateTimeImmutable($start))->format('Y-m-d H:i:s');$end=(new \DateTimeImmutable($end))->format('Y-m-d H:i:s');$ok=(new ReservationService(App::db()))->available($unit,$start,$end);echo json_encode(['available'=>$ok],JSON_THROW_ON_ERROR);}catch(\Throwable){http_response_code(422);echo '{"available":false}';}}
}
