<?php
declare(strict_types=1);
namespace Arcates\Controllers;
use Arcates\Core\AdminView;use Arcates\Core\App;use Arcates\Core\Csrf;use Arcates\Core\Security;
final class ShippingAdminController
{
 public function index(): void{AdminView::header('Kargo ve kuponlar');$a=Security::escape((string)App::config('app.admin_path','yonetim'));echo '<form class="card" method="post" action="/'.$a.'/kargo/ekle">'.Csrf::field().'<h2>Kargo kuralı</h2><input name="name" placeholder="Kural adı" required><input type="number" step="0.01" min="0" name="min_total" placeholder="Min toplam" value="0"><input type="number" step="0.01" min="0" name="max_total" placeholder="Max toplam"><input type="number" step="0.01" min="0" name="fee" placeholder="Ücret" required><button>Ekle</button></form><form class="card" method="post" action="/'.$a.'/kupon/ekle">'.Csrf::field().'<h2>Kupon</h2><input name="code" required placeholder="KOD"><select name="type"><option value="percent">Yüzde</option><option value="fixed">Sabit</option></select><input type="number" step="0.01" min="0" name="value" required><input type="number" step="0.01" min="0" name="min_total" value="0"><button>Ekle</button></form>';foreach(App::db()->fetchAll('SELECT * FROM shipping_rules ORDER BY sort_order,id') as $r)echo '<p>'.Security::escape($r['name']).' · '.number_format((float)$r['fee'],2,',','.').' TL</p>';foreach(App::db()->fetchAll('SELECT * FROM coupons ORDER BY id DESC') as $c)echo '<p>Kupon: '.Security::escape($c['code'].' · '.$c['type']).' · '.Security::escape((string)$c['value']).'</p>';AdminView::footer();}
 public function addRule(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);App::db()->execute('INSERT INTO shipping_rules(name,min_total,max_total,fee,is_active,sort_order,created_at) VALUES(?,?,?,?,1,0,NOW())',[mb_substr(trim((string)($_POST['name']??'')),0,190),max(0,(float)($_POST['min_total']??0)),trim((string)($_POST['max_total']??''))===''?null:max(0,(float)$_POST['max_total']),max(0,(float)($_POST['fee']??0))]);$this->back();}
 public function addCoupon(): void{AdminView::requireUser();Csrf::requireValid($_POST['_csrf']??null);$code=strtoupper(trim((string)($_POST['code']??'')));$type=in_array($_POST['type']??'',['percent','fixed'],true)?(string)$_POST['type']:'fixed';if($code==='')throw new \RuntimeException('Kupon kodu gerekli.');App::db()->execute('INSERT INTO coupons(code,type,value,min_total,is_active,created_at) VALUES(?,?,?,?,1,NOW())',[mb_substr($code,0,80),$type,max(0,(float)($_POST['value']??0)),max(0,(float)($_POST['min_total']??0))]);$this->back();}
 private function back(): void{header('Location: /'.App::config('app.admin_path','yonetim').'/kargo');}
}
